version: '3.7'

services:
  task-service:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@postgres/task_db
      - RABBITMQ_URL=amqp://rabbitmq

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  postgres-data:
